# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test package

on:
  push:
    branches: [ Shocker ]
  pull_request:
    branches: [ Shocker ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
       py_version: ["3.8", "3.9"] 

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.py_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py_version }}
    - name: Install dependencies
      run: |
        pip install --upgrade setuptools pip
        pip install --upgrade .
        pip install -r requirements-tests.txt
        
    - name: Run pytest with codecoverage
      run:  pytest --cov polyply --cov-report=xml
    - name: Upload coverage codecov   
      uses: codecov/codecov-action@v3 
      with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: ./coverage.xml
            fail_ci_if_error: true
            verbose: true
        
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install --upgrade setuptools pip
        pip install --upgrade .
        pip install -r requirements-tests.txt
    - name: Run pylint 
      run: |
         pylint --disable=fixme --fail-under=8 shocker
         pylint --disable=fixme --fail-under=8 bin/shocker
